binary: main
build_commit: 947f64f
build_number: 1523
cpu_has_arm_fma: true
cpu_has_avx: false
cpu_has_avx2: false
cpu_has_avx512: false
cpu_has_avx512_vbmi: false
cpu_has_avx512_vnni: false
cpu_has_blas: true
cpu_has_cublas: false
cpu_has_clblast: false
cpu_has_fma: false
cpu_has_gpublas: false
cpu_has_neon: true
cpu_has_f16c: false
cpu_has_fp16_va: true
cpu_has_wasm_simd: false
cpu_has_blas: true
cpu_has_sse3: false
cpu_has_vsx: false
debug: false
model_desc: stablelm 3B mostly F16 (guessed)
n_vocab: 50304  # output size of the final layer, 32001 for some models
optimize: true
time: 2024_01_31-21_33_00.9801635210

###############
# User Inputs #
###############

alias: unknown # default: unknown
batch_size: 512 # default: 512
cfg_negative_prompt:
cfg_scale: 1.000000 # default: 1.0
chunks: -1 # default: -1 (unlimited)
color: false # default: false
ctx_size: 512 # default: 512
escape: false # default: false
file: # never logged, see prompt instead. Can still be specified for input.
frequency_penalty: 0.000000 # default: 0.0 
grammar:
grammar-file: # never logged, see grammar instead. Can still be specified for input.
hellaswag: false # default: false
hellaswag_tasks: 400 # default: 400
ignore_eos: false # default: false
in_prefix:
in_prefix_bos: false # default: false
in_suffix:
instruct: false # default: false
interactive: false # default: false
interactive_first: false # default: false
keep: 0 # default: 0
logdir: /Users/zhangyadong/jeffproject/AthenaCoder/extensions/athenacoder/resources/ # default: unset (no logging)
logit_bias:
lora:
lora_scaled:
lora_base: 
main_gpu: 0 # default: 0
memory_f32: false # default: false
mirostat: 0 # default: 0 (disabled)
mirostat_ent: 5.000000 # default: 5.0
mirostat_lr: 0.100000 # default: 0.1
mlock: false # default: false
model: /Users/zhangyadong/jeffproject/AthenaCoder/extensions/athenacoder/resources/main/stable-code-3b.gguf # default: models/7B/ggml-model.bin
model_draft:  # default:
multiline_input: false # default: false
n_gpu_layers: -1 # default: -1
n_predict: -1 # default: -1 (unlimited)
n_probs: 0 # only used by server binary, default: 0
no_mmap: false # default: false
no_mul_mat_q: false # default: false
no_penalize_nl: false # default: false
numa: false # default: false
ppl_output_type: 0 # default: 0
ppl_stride: 0 # default: 0
presence_penalty: 0.000000 # default: 0.0
prompt: write a bubble sort in c
prompt_cache: 
prompt_cache_all: false # default: false
prompt_cache_ro: false # default: false
prompt_tokens: [6343, 247, 19251, 3686, 275, 260]
random_prompt: false # default: false
repeat_penalty: 1.100000 # default: 1.1
reverse_prompt:
rope_freq_base: 0.000000 # default: 10000.0
rope_freq_scale: 0.000000 # default: 1.0
seed: 1706707960 # default: -1 (random seed)
simple_io: false # default: false
cont_batching: false # default: false
temp: 0.800000 # default: 0.8
tensor_split: [0.000000e+00]
tfs: 1.000000 # default: 1.0
threads: 4 # default: 8
top_k: 40 # default: 40
top_p: 0.950000 # default: 0.95
min_p: 0.050000 # default: 0.0
typical_p: 1.000000 # default: 1.0
verbose_prompt: false # default: false

######################
# Generation Results #
######################

output: "++\n#include <iostream>\nusing namespace std;\n\n int main() {\n 	int n,i,temp;\n 	cout<<\"Enter number of elements: \";\n 	cin>>n;\n \n 	int arr[1000];\n \n 	for(i=0; i<n; ++i)\n 		 cin >> arr [i] ;\n 	 \n 	 for (i = 1 ; i < n ; ++i )\n{\ntemp = arr [i - 1 ] ;\narr [i - 1 ] = arr [i] ;\narr [i ] = temp ;\n}\n \n 	for(i=0; i<n; ++i)\n 		 cout << arr[i] << \" \";\n \n 	return 0;\n }\n\n"
output_tokens: [3424, 187, 4, 3709, 654, 74, 33203, 31, 187, 5302, 12953, 6268, 28, 535, 540, 2022, 1082, 551, 586, 186, 565, 295, 13, 74, 13, 16306, 28, 586, 186, 28644, 14193, 3, 15886, 1180, 273, 3603, 27, 36417, 586, 186, 5620, 5064, 79, 28, 12593, 186, 565, 4077, 60, 9138, 2194, 12593, 186, 1542, 9, 74, 30, 17, 28, 891, 29, 79, 28, 12996, 74, 10, 586, 623, 15573, 11396, 4077, 544, 74, 62, 3706, 586, 186, 4928, 186, 323, 313, 74, 426, 337, 3706, 891, 654, 295, 3706, 12996, 74, 2387, 187, 50276, 92, 187, 50274, 16306, 426, 4077, 544, 74, 428, 337, 5032, 3706, 187, 50274, 3298, 544, 74, 428, 337, 5032, 426, 4077, 544, 74, 62, 3706, 187, 50274, 3298, 544, 74, 5032, 426, 14712, 3706, 187, 50276, 94, 12593, 186, 1542, 9, 74, 30, 17, 28, 891, 29, 79, 28, 12996, 74, 10, 586, 623, 31374, 5291, 4077, 60, 74, 62, 5291, 346, 36417, 12593, 186, 2309, 470, 28, 187, 748, 535, 0]

###########
# Timings #
###########

mst_eval: 74.99  # ms / token during generation
mst_p_eval: 14.21  # ms / token during prompt processing
mst_sample: 0.43  # ms / token during sampling
n_eval: 166  # number of tokens generated (excluding the first one)
n_p_eval: 6  # number of tokens processed in batches at the beginning
n_sample: 167  # number of sampled tokens
t_eval_us: 12448739  # total microseconds spent generating tokens
t_load_us: 7338903  # total microseconds spent loading the model
t_p_eval_us: 85234  # total microseconds spent prompt processing
t_sample_us: 72342  # total microseconds spent sampling
ts_eval: 13.33  # tokens / second during generation
ts_p_eval: 70.39  # tokens / second during prompt processing
ts_sample: 2308.48  # tokens / second during sampling
